apiVersion: v1
kind: Service
metadata:
  name: dot-net-app
  # namespace: devops
spec:
  selector: 
    app: dot-net-app
  type: LoadBalancer  
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
