apiVersion: v1
kind: Service
metadata:
  name: dot-net-app
  namespace: devops
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path:   /
      prometheus.io/port:   '8080'
spec:
  selector: 
    app: dot-net-app
  type: LoadBalancer  
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
      
      